### ISSUE TITLE
Missing transaction types for binance

### ISSUE THREAD

**Issue by LEBT48** [provinzio/CoinTaxman#1]
2021-02-16 20:58:08,868 book         INFO     Reading file from exchange binance at account_statements\test_input.csv
2021-02-16 20:58:08,872 book         WARNING  Could not recognize operation `Transaction Related` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,874 book         WARNING  Could not recognize operation `Transaction Related` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,876 book         WARNING  Could not recognize operation `The Easiest Way to Trade` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,876 book         WARNING  Could not recognize operation `The Easiest Way to Trade` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,877 book         WARNING  Could not recognize operation `Small assets exchange BNB` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,880 book         WARNING  Could not recognize operation `Small assets exchange BNB` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,880 book         WARNING  Could not recognize operation `Transaction Related` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,881 book         WARNING  Could not recognize operation `Transaction Related` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,882 book         WARNING  Could not recognize operation `Transaction Related` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,882 book         WARNING  Could not recognize operation `Transaction Related` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,885 book         WARNING  Could not recognize operation `Small assets exchange BNB` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,885 book         WARNING  Could not recognize operation `Small assets exchange BNB` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,886 book         WARNING  Could not recognize operation `Transaction Related` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,886 book         WARNING  Could not recognize operation `Transaction Related` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,888 book         WARNING  Could not recognize operation `Small assets exchange BNB` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,888 book         WARNING  Could not recognize operation `Small assets exchange BNB` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,889 book         WARNING  Could not recognize operation `Transaction Related` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,890 book         WARNING  Could not recognize operation `Transaction Related` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,892 book         WARNING  Could not recognize operation `Small assets exchange BNB` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,892 book         WARNING  Could not recognize operation `Small assets exchange BNB` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,894 book         WARNING  Could not recognize operation `Small assets exchange BNB` in binance file `account_statements\test_input.csv`.
2021-02-16 20:58:08,907 book         WARNING  Could not recognize operation `Small assets exchange BNB` in binance file `account_statements\test_input.csv`.
Traceback (most recent call last):
  File "C:\CoinTaxman-main\src\taxman.py", line 78, in _evaluate_taxation_GERMANY
    sold_coins = bilance.sell(op.change)
  File "C:\CoinTaxman-main\src\bilance_queue.py", line 118, in sell
    bop: BilancedOperation = self.get()
  File "C:\CoinTaxman-main\src\bilance_queue.py", line 67, in get
    return self._get()
  File "C:\CoinTaxman-main\src\bilance_queue.py", line 73, in _get
    return self.queue.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\CoinTaxman-main\src\main.py", line 43, in <module>
    main()
  File "C:\CoinTaxman-main\src\main.py", line 38, in main
    taxman.evaluate_taxation()
  File "C:\CoinTaxman-main\src\taxman.py", line 130, in evaluate_taxation
    self.__evaluate_taxation(coin, operations)
  File "C:\CoinTaxman-main\src\taxman.py", line 82, in _evaluate_taxation_GERMANY
    raise RuntimeError(
RuntimeError: Not enough BTC in queue to remove sold ones.
[test_input.zip](https://github.com/provinzio/CoinTaxman/files/5991379/test_input.zip)

**Comment by provinzio** [comment]
I extended the supported operations for the binance import. All of your mentioned operations should work now.

I saw, that you have some BTC deposits in your test file. If you are missing the corresponding Withdrawls, you might get calculation errors (if you sell these coins somewhere else later).
