### ISSUE TITLE
Issues with commission

### ISSUE THREAD

**Issue by KonstantinPasternack** [provinzio/CoinTaxman#10]
Does not seem to work for the following file. Statement is from binance. Adjustments I made: tax year 2021. All else was left as it is.

UTC_Time,Account,Operation,Coin,Change,Remark
2021-01-01 00:41:08,Spot,Buy,USDT,11.35763200,""
2021-01-01 00:41:08,Spot,Commission Fee Shared With You,USDT,0.00227153,""
2021-01-01 00:41:08,Spot,Fee,USDT,-0.01135763,""
2021-01-01 00:41:08,Spot,Sell,KNC,-14.14400000,""
2021-01-01 01:28:56,Spot,Fee,USDT,-0.01123540,""
2021-01-01 01:28:56,Spot,Commission Fee Shared With You,USDT,0.00224708,""
2021-01-01 01:28:56,Spot,Buy,USDT,11.23540200,""
2021-01-01 01:28:56,Spot,Sell,EUR,-9.18000000,""
2021-01-01 07:12:37,Spot,Buy,DOT,2.54000000,""
2021-01-01 07:12:37,Spot,Sell,USDT,-22.30932800,""
2021-01-01 07:12:37,Spot,Commission Fee Shared With You,DOT,0.00050800,""
2021-01-01 07:12:37,Spot,Fee,DOT,-0.00254000,""
2021-01-01 07:24:08,Spot,Commission Fee Shared With You,USDT,0.00454069,""
2021-01-01 07:24:08,Spot,Sell,DOT,-2.53000000,""
2021-01-01 07:24:08,Spot,Buy,USDT,22.70346100,""
2021-01-01 07:24:08,Spot,Fee,USDT,-0.02270346,""
2021-01-01 11:10:45,Spot,Commission Fee Shared With You,USDC,0.00457800,""
2021-01-01 11:10:45,Spot,Fee,USDC,-0.02289000,""
2021-01-01 11:10:45,Spot,Buy,USDC,22.89000000,""
2021-01-01 11:10:45,Spot,Sell,USDT,-22.83506400,""
2021-01-01 13:43:24,Spot,Fee,USDT,-0.02282197,""
2021-01-01 13:43:24,Spot,Buy,USDT,22.82197300,""
2021-01-01 13:43:24,Spot,Commission Fee Shared With You,USDT,0.00456440,""
2021-01-01 13:43:24,Spot,Sell,USDC,-22.87000000,""
2021-01-01 14:32:00,Spot,Sell,USDT,-22.80811800,""
2021-01-01 14:32:00,Spot,Fee,XEM,-0.10574000,""
2021-01-01 14:32:00,Spot,Commission Fee Shared With You,XEM,0.02114800,""
2021-01-01 14:32:00,Spot,Buy,XEM,105.74000000,""
2021-01-01 15:54:01,Spot,Sell,XEM,-105.65000000,""
2021-01-01 15:54:01,Spot,Buy,USDT,23.17961000,""
2021-01-01 15:54:01,Spot,Fee,USDT,-0.02317961,""
2021-01-01 15:54:01,Spot,Commission Fee Shared With You,USDT,0.00463592,""
2021-01-01 16:03:24,Spot,Transaction Related,EUR,-200.00000000,""
2021-01-01 16:03:24,Spot,Transaction Related,USDT,243.28597000,""
2021-01-01 17:22:49,Spot,Sell,USDT,-49.86327600,""

I'm getting the following error:

PS C:\Users\k\coding\CryptoTaxMan\CoinTaxman\src> py .\main.py
2021-02-23 23:24:49,197 book         INFO     Reading file from exchange binance at C:\Users\k\coding\CryptoTaxMan\CoinTaxman\account_statements\part-00000-9de92497-2081-408b-a4c2-981f99a7c440-c000.csv
Traceback (most recent call last):
  File "C:\Users\k\coding\CryptoTaxMan\CoinTaxman\src\main.py", line 44, in <module>
    main()
  File "C:\Users\k\coding\CryptoTaxMan\CoinTaxman\src\main.py", line 32, in main
    status = book.read_files()
  File "C:\Users\k\coding\CryptoTaxMan\CoinTaxman\src\book.py", line 257, in read_files
    self.read_file(file_path)
  File "C:\Users\k\coding\CryptoTaxMan\CoinTaxman\src\book.py", line 217, in read_file
    read_file(file_path)
  File "C:\Users\k\coding\CryptoTaxMan\CoinTaxman\src\book.py", line 79, in _read_binance
    for _utc_time, account, operation, coin, _change, remark in reader:
ValueError: not enough values to unpack (expected 6, got 0)

**Comment by provinzio** [comment]
I am currently not at home and can not debug this properly. Your error states, that the program is not able to read 6 values from a line (it got 0).

This might occur because of an empty ending line. Or an empty line in the middle of the file. Have you edited the file?

If your want to debug it yourself. Add `print(row)` in the second line of the loop (after the row declaration row=...line_number). And check the line after which the error raises.

**Comment by KonstantinPasternack** [comment]
Sorry for the late reply,
Thanks for that tip. It pointed me to the issues. There seem to be multiple.
The file was not edited, just shortened, as testing with 11.000 trades seems a bit much to start with :D
I'll attach the file here. So you can have a look for yourself. I'm still learning python so any help is appriciated.
([account_statement_binance.zip](https://github.com/provinzio/CoinTaxman/files/6057917/account_statement_binance.zip))

**Comment by provinzio** [comment]
I see that you did `Large OTC trading`. I am currently unsure, if this kind of trading is taxed the same as a normal trade. Do you now any thing about it?

You have to add the missing trades (from the wallet from where you migrated your positions). Otherwhise the program is unable to calculate your correct taxes.

**Comment by KonstantinPasternack** [comment]
Actually all trading I do is exchange based. I just switched the exchange some time in. So I'm not sure, where you get the OTC trading from. In my interpretation from the German tax laws, it wouldn't make a difference anyways. In each case they're "private Veräußerungsgeschäfte".

What you're saying is, that I should manually change the binance account statement, which I think would be very error prone.

It would be much more comfortable, if taxman would just "ignore" statements it cannot match and log them out separately, but otherwise complete the tax statement. In my case, this would probably give me a correct approximation for almost all transactions and would leave 20 odd for manual correction.

**Comment by provinzio** [comment]
The current behavior is as you described. Unknown operations are ignored with da warning. 
https://github.com/provinzio/CoinTaxman/blob/1f465e941393d58de067f09d4d6cad88f732fed5/src/book.py#L57

I'll add the OTC tag, since you clarified the taxation for it.

**Comment by provinzio** [comment]
This should fix all current problems related to the issue.
