### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by pstuermlinger** [provinzio/CoinTaxman#107]
Hi guys,
I'm getting the following error:
```
python3 src/main.py 
Traceback (most recent call last):
  File "src/main.py", line 18, in <module>
    from book import Book
  File "/home/haggis/tmp/CoinTaxman/src/book.py", line 26, in <module>
    import misc
  File "/home/haggis/tmp/CoinTaxman/src/misc.py", line 40, in <module>
    L = TypeVar("L", bound=list[Any])
TypeError: 'type' object is not subscriptable
```
Under `account_statements` I put a csv starting with the following line:
`User_ID,UTC_Time,Account,Operation,Coin,Change,Remark`

Any ideas?

**Comment by provinzio** [comment]
Please check your python version. You need at least 3.9

**Comment by pstuermlinger** [comment]
That's it. Thanks!
