### ISSUE TITLE
Order subtype 'spotfromfutures' is currently not supported

### ISSUE THREAD

**Issue by alexanderadam** [provinzio/CoinTaxman#158]
Hello @provinzio,

I tried to calculate the statements for Kraken and I'm getting the error message `Order subtype 'spotfromfutures' is currently not supported`.
Do you have any advice on what I should do?

```
52,245 book         ERROR    /home/user/projects/CoinTaxman/account_statements/ledgers.csv row 297: Order subtype 'spotfromfutures' is currently not supported. Please create an Issue or PR.
Traceback (most recent call last):
  File "/home/user/projects/CoinTaxman/src/main.py", line 71, in <module>
    main()
  File "/home/user/projects/CoinTaxman/src/main.py", line 36, in main
    status = book.read_files()
             ^^^^^^^^^^^^^^^^^
  File "/home/user/projects/CoinTaxman/src/book.py", line 1778, in read_files
    self.read_file(file_path)
  File "/home/user/projects/CoinTaxman/src/book.py", line 1730, in read_file
    read_file(file_path)
  File "/home/user/projects/CoinTaxman/src/book.py", line 670, in _read_kraken_ledgers
    raise RuntimeError
RuntimeError
```

Thank you in advance!

**Comment by provinzio** [comment]
Hey, the transaction type has to be mapped to an operation type. 

For that it's necessary to understand what 'spotfromfutures' means. Is it a transfer between spot and futures wallet? Or a buy/sell action?

Feel free to checkout the operations mapping near the erroring line.
