### ISSUE TITLE
Fail to import Kraken-ledger

### ISSUE THREAD

**Issue by Albrecht1984** [provinzio/CoinTaxman#56]
Win10, 64 bit
Python 3.9.5150.1013

certifi | 2020.12.5 | 2021.5.30
chardet | 4.0.0 | 4.0.0
idna | 2.10 | 3.2
pip | 21.1.2 | 21.1.2
python-dateutil | 2.8.1 | 2.8.1
requests | 2.25.1 | 2.25.1
setuptools | 57.0.0 | 57.0.0
six | 1.15.0 | 1.16.0
urllib3 | 1.26.5 | 1.26.5

Hello!
I tried to import a brandnew kraken ledger, but when I start main.py an error occurs. What may be the problem?
The console reads

"C:\Users\Hugos Dell\PycharmProjects\Steuer\Scripts\python.exe" "C:/Users/Hugos Dell/PycharmProjects/Steuer/CoinTaxman-main/src/main.py"
2021-06-20 23:16:52,068 book         INFO     Reading file from exchange kraken_ledgers at C:\Users\Hugos Dell\PycharmProjects\Steuer\CoinTaxman-main\account_statements\ledgers.csv
2021-06-20 23:16:52,073 taxman       DEBUG    Starting evaluation...
2021-06-20 23:16:52,073 taxman       WARNING  Balance has outstanding fees which were not considered: 31.0797 EUR
Traceback (most recent call last):
  File "C:\Users\Hugos Dell\PycharmProjects\Steuer\CoinTaxman-main\src\main.py", line 44, in <module>
    main()
  File "C:\Users\Hugos Dell\PycharmProjects\Steuer\CoinTaxman-main\src\main.py", line 39, in main
    taxman.export_evaluation_as_csv()
  File "C:\Users\Hugos Dell\PycharmProjects\Steuer\CoinTaxman-main\src\taxman.py", line 234, in export_evaluation_as_csv
    if commit_hash := misc.get_current_commit_hash():
  File "C:\Users\Hugos Dell\PycharmProjects\Steuer\CoinTaxman-main\src\misc.py", line 236, in get_current_commit_hash
    subprocess.check_output(["git", "rev-parse", "HEAD"])
  File "D:\Programme\python\python3_9\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\Programme\python\python3_9\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Programme\python\python3_9\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Programme\python\python3_9\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

Process finished with exit code 1

Thank you for your help

**Comment by provinzio** [comment]
> File "C:\Users\Hugos Dell\PycharmProjects\Steuer\CoinTaxman-main\src\taxman.py", line 234, in export_evaluation_as_csv
if commit_hash := misc.get_current_commit_hash():

Python can not find an git Installation on your system. This error is unwanted. 

You can quick fix it, by for example replacing the code after if with `True`. So it is just `if True:`

**Comment by provinzio** [comment]
The newest commit should avoid the exception.
